household_power_consumption <- read.csv("household_power_consumption.txt", sep=";", na.strings="?")
household_power_consumption$Date <- as.Date(household_power_consumption$Date, format ="%d/%m/%Y")
df<-subset(household_power_consumption, (household_power_consumption$Date == "2007-02-01")|(household_power_consumption$Date =="2007-02-02"))
df$g<- paste(df$Date, df$Time)
df$DateTime <- strptime(df$g, "%Y-%m-%d %H:%M:%S")
png(filename = "plot1.png", width = 480, height = 480)
hist(df$Global_active_power, col = "red", main = "Global Active Power", xlab = "Global Active Power(kilowatts)")
dev.off()

png(filename = "plot2.png", width = 480, height = 480)
plot(df$DateTime, df$Global_active_power, ylab = "Global Active Power(kilowatts)", xlab = "", type = "l")
dev.off()

png(filename = "plot3.png", width = 480, height = 480)
plot(df$DateTime, df$Sub_metering_1, ylab = "Energy sub metering",xlab = "", type = "n")
points(df$DateTime, df$Sub_metering_1,type = "l")
points(df$DateTime, df$Sub_metering_2,type = "l", col = "red")
points(df$DateTime, df$Sub_metering_3,type = "l", col = "blue")
legend("topright", c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"), col = c("black","red","blue"), lty = c(1,1,1))
dev.off()

par("mfrow" = c(2,2))
plot(df$DateTime, df$Global_active_power, ylab = "Global Active Power", xlab = "", type = "l")
plot(df$DateTime, df$Voltage, ylab = "Voltage", xlab = "datetime", type = "l")
plot(df$DateTime, df$Sub_metering_1, ylab = "Energy sub metering",xlab = "", type = "n")
points(df$DateTime, df$Sub_metering_1,type = "l")
points(df$DateTime, df$Sub_metering_2,type = "l", col = "red")
points(df$DateTime, df$Sub_metering_3,type = "l", col = "blue")
plot(df$DateTime, df$Global_reactive_power , ylab = "Global_reactive_power", xlab = "datetime", type = "l")
dev.off
